### PR TITLE
made some adjustments to initial menu

### PR DESCRIPTION
**Pull request by ga402**
1. adjusted some spelling
2. put the initial menu into a loop, so that is doesn't crash out
3. put the initial menu options into a separate function so it can be called at different times

### CODE REVIEW

**Comment by florisvanrijn** [comment]
@shadi-git ,
I'm running into some issues running the code locally, mainly being that I can't seem to authenticate with any of the standard accounts already in the 'db'. Is this something you're getting on your end as well? 
Steps to reproduce:
run both server + client,
press 1 to log in as existing user,
use 'Bhagy' as username + 'password' as password.
Expected result: Screen allowing for inputs 
Actual result: loop of 'null' being printed to screen

**Comment by ga402** [comment]
@florisvanrijn I think the issue was that Bhagy's password didn't fit the criteria for a appropriate password. I've created a branch in which I simply add an uppercase letter to the password and it works fine.

**Comment by florisvanrijn** [comment]
Nice find! I think I could've spent hours looking at it and not seeing it. I didn't realise password strengths were upheld even after it's set.
If password strength is checked at the time of log-in it may be worth altering in a future release as password strength (in my mind) should be checked at the time it's set, but whatever password an account has shouldn't stop the from logging in.
Although this would only ever be a problem for accounts that are 'pre-installed' in our db so it's also never really going to be a problem.
Still, program flow wise I think it would make more sense.

What do you think?

**Comment by ga402** [comment]
Yeah - I completely agree. Password strength should be checked at the time its set - but as you point out, this issue should only be a problem for the 'pre-set' test passwords....

**Comment by shadi-git** [comment]
Great catch. Thanks George @ga402! And I completely agree with all the above ^^^...

**Pull request merged**
